services:
  admin-ui-builder:
    build:
      context: ../offerly-admin-ui
      dockerfile: Dockerfile
    volumes:
      - offerly-admin-ui-build:/app/dist
    command: echo "Admin UI build complete"
    networks:
      - offerly-network
  api:
    container_name: offerly-api-c
    build:
      context: ../offerly-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - DB_URL=${DB_URL}
        - DATA_DIR=${DATA_DIR}
        - UPLOADS_DIR=${UPLOADS_DIR}
        - COUNTRIES=${COUNTRIES}
        - CATEGORIES=${CATEGORIES}
        - LANGUAGES=${LANGUAGES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=${DB_URL}
      - DATA_DIR=${DATA_DIR}
      - UPLOADS_DIR=${UPLOADS_DIR}
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
    networks:
      - offerly-network
  nginx:
    container_name: offerly-nginx-c
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - offerly-admin-ui-build:/usr/share/nginx/html
    depends_on:
      - admin-ui-builder
      - api
    networks:
      - offerly-network

networks:
  offerly-network:
    external:
      name: offerly-network

volumes:
  offerly-admin-ui-build:
  offerly-db-data:
  offerly-uploads:
