services:
  admin-ui-builder:
    build:
      context: ../offerly-admin-ui
      dockerfile: Dockerfile
    volumes:
      - offerly-admin-web-build:/app/dist
  offerly-api:
    container_name: offerly-api-c
    env_file:
      - .env
    environment:
      - PORT=8000
      - NODE_ENV=production
    restart: unless-stopped
    build:
      context: ../offerly-api
      dockerfile: Dockerfile
      args:
        - UPLOADS_DIR=${UPLOADS_DIR}
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
    networks:
      - services-net
  nginx:
    container_name: offerly-nginx-c
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - offerly-admin-web-build:/usr/share/nginx/offerly/admin
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logo.png:/usr/share/nginx/offerly/assets/logo.png
      - /etc/letsencrypt/live/api.offerly.me/fullchain.pem:/etc/letsencrypt/live/api.offerly.me/fullchain.pem:ro
      - /etc/letsencrypt/live/api.offerly.me/privkey.pem:/etc/letsencrypt/live/api.offerly.me/privkey.pem:ro
      - /etc/letsencrypt/live/admin.offerly.me/fullchain.pem:/etc/letsencrypt/live/admin.offerly.me/fullchain.pem:ro
      - /etc/letsencrypt/live/admin.offerly.me/privkey.pem:/etc/letsencrypt/live/admin.offerly.me/privkey.pem:ro
    depends_on:
      - admin-ui-builder
      - offerly-api
    networks:
      - services-net
  offerly-scrappers:
    container_name: offerly-scrappers-c
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8001
    build:
      context: ../offerly-scrappers
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - services-net
  offerly-redis:
    container_name: offerly-redis-c
    restart: unless-stopped
    image: redis:7.4.2-alpine
    networks:
      - services-net
networks:
  services-net:
    name: offerly-network
    external: true

volumes:
  offerly-admin-web-build:
  offerly-uploads:
    external: true
    name: offerly-uploads
