services:
  admin-ui-builder:
    build:
      context: ../offerly-admin-ui
      dockerfile: Dockerfile
    volumes:
      - offerly-admin-web-build:/app/dist
  offerly-api:
    container_name: offerly-api-c
    build:
      context: ../offerly-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - DB_URL=${DB_URL}
        - DATA_DIR=${DATA_DIR}
        - UPLOADS_DIR=${UPLOADS_DIR}
        - COUNTRIES=${COUNTRIES}
        - CATEGORIES=${CATEGORIES}
        - LANGUAGES=${LANGUAGES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=${DB_URL}
      - DATA_DIR=${DATA_DIR}
      - UPLOADS_DIR=${UPLOADS_DIR}
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
    restart: always
  nginx:
    container_name: offerly-nginx-c
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - offerly-admin-web-build:/usr/share/nginx/offerly/admin
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - admin-ui-builder
      - offerly-api
    restart: always

  certbot:
    container_name: offerly-certbot-c
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  default:
    external: true
    name: offerly-network

volumes:
  offerly-admin-web-build:
  offerly-uploads:
    external: true
    name: offerly-uploads
