services:
  admin-ui-builder:
    build:
      context: ../offerly-admin-ui
      dockerfile: Dockerfile
    volumes:
      - offerly-admin-web-build:/app/dist
  offerly-api:
    container_name: offerly-api-c
    build:
      context: ../offerly-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - DB_URL=${DB_URL}
        - DATA_DIR=${DATA_DIR}
        - UPLOADS_DIR=${UPLOADS_DIR}
        - COUNTRIES=${COUNTRIES}
        - CATEGORIES=${CATEGORIES}
        - LANGUAGES=${LANGUAGES}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=${DB_URL}
      - DATA_DIR=${DATA_DIR}
      - UPLOADS_DIR=${UPLOADS_DIR}
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
  nginx:
    container_name: offerly-nginx-c
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - offerly-admin-web-build:/usr/share/nginx/offerly/admin
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt/archive/www.offerly.me/fullchain.pem:/certs/fullchain1.pem:ro
      - /etc/letsencrypt/archive/www.offerly.me/privkey.pem:/certs/privkey1.pem:ro
    depends_on:
      - admin-ui-builder
      - offerly-api

networks:
  default:
    external: true
    name: offerly-network

volumes:
  offerly-admin-web-build:
  offerly-uploads:
    external: true
    name: offerly-uploads
